### ISSUE TITLE
Add a travis worker with sge

### ISSUE THREAD

**Issue by arjoly** [clusterlib/clusterlib#18]
Here some references: 

- https://scidom.wordpress.com/2012/01/18/sge-on-single-pc/
- https://gist.github.com/dan-blanchard/6586533
- https://github.com/drmaa-python/drmaa-python/blob/master/travis/install_sge.sh

**Comment by arjoly** [comment]
It will probably require to do some conditional matrix travis worker as done in scikit-learn https://github.com/scikit-learn/scikit-learn/blob/master/.travis.yml

**Comment by arjoly** [comment]
> It will probably require to do some conditional matrix travis worker as done in scikit-learn https://github.com/scikit-learn/scikit-learn/blob/master/.travis.yml

This is done in 53330787d33be4b27d474d98cfea58053727734f

**Comment by arjoly** [comment]
Done in #22

**Comment by ogrisel** [comment]
:beers: :
